theme: jekyll-theme-hacker

title: Arkadyax Software
description: Startup software company based all over the world!

plugins:
  - jekyll-mentions

collections: # These are things that are a group of associated items, like all the products or all the blog post
  products: # Includes both open and closed source projects
  monthly: # Includes both game and code of the month
    output: false # Dont render as webpages, we only want to store the data
    permalink: /:collection/:name

collections_dir: _collections

github_url: https://github.com/Arkadyax
facebook_url: https://www.facebook.com/arkadyaxsw
twitter_url: https://twitter.com/arkadyax

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass
  
team:
- name: Lukas Woodruff
  role: CEO
  github: mentalvenom
  email: replitcode # the @arkadyax.cf is added automatically

- name: Elias Bomberger
  role: Vice President
  github: ebomberger23
  email: elias

- name: Ibraheem Rodrigues
  role: Chief Operations Officer
  github: IbraheemR
  email: oban

- name: Mitchell
  role: Chief Visionary Officer
  github: Moopirs
  email: moopy

- name: HappyFakeBoulder
  role: Marketing Manager
  github: HappyFakeBoulder
  email: happyfakeboulder

- name: Shane Vandegrift
  role: Campaign Manager
  github: Vandesm14
  email: vandesm14
  
- name: Caleb
  role: Chief Software Developer
  github: jslol
  email: caleb
  
- name: Haya Odeh
  role: Designer
  github: hayaodeh
  email: hayaodeh
